export default function Head() {
  return (
    <>
      <title>PIAIC</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://www.piaic.org/static/media/Logo.fb7de414.svg" />
    </>
  )
}
